### ISSUE TITLE
Support staging environment

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-batchrobot#13]
When running in staging, this integration should send to the staging BatchRobot URL. The [SuppressionList integration](https://github.com/activeprospect/leadconduit-integration-suppressionlist/blob/77257715d09e34b8d9d3f841a415d8a094f0e7fc/src/helper.coffee#L62-L66) provides an example on how this works.

**Comment by alexkwolfe** [comment]
Hey @jgrayson676, is this something that could be done fairly quickly? It would help us get the feedback feature properly tested and released.

**Comment by alexkwolfe** [comment]
The URL for BatchRobot in staging is http://staging.app.batchrobot.com/.

**Comment by jgrayson676** [comment]
Sure
